import { ChefHat, Wine, Coffee } from "lucide-react";
import { type MenuData, type FilterOption } from "./types";

export const fullMenuData: MenuData = {
  "menu-principal": {
    id: "menu-principal",
    name: "Menú Principal",
    subtitle: "Restaurante 'El Sabor'",
    icon: ChefHat,
    color: "bg-orange-50 border-orange-200",
    iconColor: "text-orange-600",
    categories: [
      {
        name: "Entradas",
        description: "Perfectas para abrir el apetito",
        dishes: [
          {
            id: "e1",
            name: "Ensalada Caprese",
            description:
              "Tomate, mozzarella fresca, albahaca y aceite de oliva virgen",
            price: "€12.50",
            time: "10 min",
            rating: 4.8,
            isVegetarian: true,
            isGlutenFree: true,
            image:
              "/images/ensalada-caprese-tomates-maduros-queso-mozzarella-hojas-albahaca-fresca-166116-3714.webp",
          },
          {
            id: "e2",
            name: "Carpaccio de Pulpo",
            description: "Láminas de pulpo con aceite de oliva, limón y rúcula",
            price: "€16.90",
            time: "15 min",
            rating: 4.9,
            isVegetarian: false,
            isGlutenFree: true,
            image: "/images/Carpaccio de Pulpo.webp",
          },
          {
            id: "e3",
            name: "Sopa de Cebolla Gratinada",
            description:
              "Tradicional sopa francesa con queso gruyere gratinado",
            price: "€9.80",
            time: "20 min",
            rating: 4.6,
            isVegetarian: true,
            isGlutenFree: false,
            image: "/images/Sopa de Cebolla Gratinada.webp",
          },
        ],
      },
      {
        name: "Platos Fuertes",
        description: "Nuestras especialidades de la casa",
        dishes: [
          {
            id: "pf1",
            name: "Salmón a la Plancha con Espárragos",
            description:
              "Salmón fresco con espárragos verdes y salsa de mantequilla al limón",
            price: "€24.50",
            time: "25 min",
            rating: 4.9,
            isVegetarian: false,
            isGlutenFree: true,
            image: "/images/Salmón a la Plancha con Espárragos.webp",
          },
          {
            id: "pf2",
            name: "Solomillo de Ternera con Reducción de Vino Tinto",
            description:
              "Solomillo premium con puré de patatas trufado y verduras de temporada",
            price: "€32.00",
            time: "30 min",
            rating: 5.0,
            isVegetarian: false,
            isGlutenFree: true,
            image:
              "/images/Solomillo de Ternera con Reducción de Vino Tinto.webp",
          },
          {
            id: "pf3",
            name: "Risotto de Setas Silvestres",
            description: "Arroz arborio con mezcla de setas, parmesano y trufa",
            price: "€18.90",
            time: "25 min",
            rating: 4.7,
            isVegetarian: true,
            isGlutenFree: false,
            image: "/images/Risotto de Setas Silvestres.webp",
          },
          {
            id: "pf4",
            name: "Paella Valenciana",
            description:
              "Arroz bomba con pollo, conejo, judías verdes y azafrán",
            price: "€22.00",
            time: "35 min",
            rating: 4.8,
            isVegetarian: false,
            isGlutenFree: true,
            isSpicy: true,
            image: "/images/Paella Valenciana.webp",
          },
        ],
      },
      {
        name: "Postres",
        description: "El final perfecto para tu comida",
        dishes: [
          {
            id: "p1",
            name: "Tarta de Queso con Frutos Rojos",
            description:
              "Cremosa tarta de queso philadelphia con coulis de frutos rojos",
            price: "€8.50",
            time: "5 min",
            rating: 4.8,
            isVegetarian: true,
            isGlutenFree: false,
            image: "/images/Tarta de Queso con Frutos Rojos.webp",
          },
          {
            id: "p2",
            name: "Brownie de Chocolate con Helado",
            description:
              "Brownie tibio con helado de vainilla y salsa de chocolate",
            price: "€7.90",
            time: "8 min",
            rating: 4.9,
            isVegetarian: true,
            isGlutenFree: false,
            image: "/images/Brownie.webp",
          },
          {
            id: "p3",
            name: "Mousse de Maracuyá",
            description: "Ligera mousse tropical con crujiente de galleta",
            price: "€6.80",
            time: "5 min",
            rating: 4.6,
            isVegetarian: true,
            isGlutenFree: true,
            image:
              "/images/Ligera mousse tropical con crujiente de galleta.webp",
          },
        ],
      },
    ],
  },
  "vinos-bebidas": {
    id: "vinos-bebidas",
    name: "Carta de Vinos",
    subtitle: "y Bebidas Premium",
    icon: Wine,
    color: "bg-purple-50 border-purple-200",
    iconColor: "text-purple-600",
    categories: [
      {
        name: "Vinos Tintos",
        description: "Selección de tintos nacionales e internacionales",
        dishes: [
          {
            id: "vt1",
            name: "Rioja Crianza",
            description: "D.O. Rioja - 12 meses en barrica de roble americano",
            price: "€28.00",
            time: "Inmediato",
            rating: 4.7,
            isVegetarian: true,
            isGlutenFree: true,
            image: "/images/Rioja Crianza.webp",
          },
          {
            id: "vt2",
            name: "Ribera del Duero Reserva",
            description: "D.O. Ribera del Duero - 18 meses en barrica",
            price: "€35.00",
            time: "Inmediato",
            rating: 4.9,
            isVegetarian: true,
            isGlutenFree: true,
            image: "/images/Ribera del Duero Reserva.webp",
          },
        ],
      },
      {
        name: "Vinos Blancos",
        description: "Frescos y aromáticos",
        dishes: [
          {
            id: "vb1",
            name: "Albariño",
            description: "D.O. Rías Baixas - Fresco y mineral",
            price: "€24.00",
            time: "Inmediato",
            rating: 4.6,
            isVegetarian: true,
            isGlutenFree: true,
            image: "/images/albadoriño.webp",
          },
        ],
      },
    ],
  },
  "desayuno-buffet": {
    id: "desayuno-buffet",
    name: "Desayuno Buffet",
    subtitle: "Opciones Matutinas",
    icon: Coffee,
    color: "bg-amber-50 border-amber-200",
    iconColor: "text-amber-600",
    categories: [
      {
        name: "Panadería",
        description: "Recién horneado cada mañana",
        dishes: [
          {
            id: "pan1",
            name: "Croissants",
            description: "Croissants de mantequilla recién horneados",
            price: "€3.50",
            time: "Inmediato",
            rating: 4.5,
            isVegetarian: true,
            image: "/images/Croissants.webp",
          },
          {
            id: "pan2",
            name: "Pan de Masa Madre",
            description: "Pan artesanal con masa madre natural",
            price: "€4.20",
            time: "Inmediato",
            rating: 4.7,
            isVegetarian: true,
            image: "/images/Pan artesanal con masa madre natural.webp",
          },
          {
            id: "pan3",
            name: "Muffins de Arándanos",
            description: "Esponjosos muffins con arándanos frescos",
            price: "€3.80",
            time: "Inmediato",
            rating: 4.4,
            isVegetarian: true,
            image: "/images/Esponjosos muffins con arándanos frescos.webp",
          },
        ],
      },
      {
        name: "Frutas y Yogures",
        description: "Opciones saludables y refrescantes",
        dishes: [
          {
            id: "fy1",
            name: "Bowl de Frutas de Temporada",
            description: "Selección diaria de frutas frescas",
            price: "€6.50",
            time: "Inmediato",
            rating: 4.6,
            isVegetarian: true,
            isGlutenFree: true,
            image: "/images/Bowl de Frutas de Temporada.webp",
          },
          {
            id: "fy2",
            name: "Yogur Griego con Miel",
            description: "Yogur cremoso con miel de lavanda y nueces",
            price: "€5.20",
            time: "Inmediato",
            rating: 4.5,
            isVegetarian: true,
            isGlutenFree: true,
            image: "/images/Yogur cremoso con miel de lavanda y nueces.webp",
          },
        ],
      },
    ],
  },
};

export const filterOptions: FilterOption[] = [
  { key: "all", label: "Todos" },
  { key: "vegetarian", label: "Vegetariano" },
  { key: "glutenFree", label: "Sin Gluten" },
  { key: "spicy", label: "Picante" },
];
